### ISSUE TITLE
Amounts should be BigDecimals

### ISSUE THREAD

**Issue by PavelNiedoba** [fireblocks/java-sdk#15]
I believe that all amounts should be BigDecimals, but there's just strings in generated code:

`
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AmountInfo {
    public static final String JSON_PROPERTY_AMOUNT = "amount";
    private String amount;

    public static final String JSON_PROPERTY_REQUESTED_AMOUNT = "requestedAmount";
    private String requestedAmount;

    public static final String JSON_PROPERTY_NET_AMOUNT = "netAmount";
    private String netAmount;

    public static final String JSON_PROPERTY_AMOUNT_U_S_D = "amountUSD";
    private String amountUSD;

    public AmountInfo() {}

    public AmountInfo amount(String amount) {
        this.amount = amount;
        return this;
    }
    ...
`

The problem seems to in OpenApi yaml, so might be easy fix but it's breaking change

```
 AmountInfo:
      description: The details of the requested amount to transfer.
      example:
        amount: amount
        amountUSD: amountUSD
        netAmount: netAmount
        requestedAmount: requestedAmount
      properties:
        amount:
          description: "If the transfer is a withdrawal from an exchange, the actual\
            \ amount that was requested to be transferred. Otherwise, the requested\
            \ amount."
          type: string
        requestedAmount:
          description: The amount requested by the user.
          type: string
        netAmount:
          description: "The net amount of the transaction, after fee deduction."
          type: string
        amountUSD:
          description: The USD value of the requested amount.
          type: string
      type: object

```
